[phases.setup]
nixPkgs = ['nodejs', 'curl']

[phases.install]
dependsOn = ['setup']
cmds = [
  'npm install -g pnpm@8',
  'pnpm install --no-frozen-lockfile'
]

[phases.build]
dependsOn = ['install']
cmds = [
  'pnpm prisma generate',
  'pnpm build'
]

[start]
cmd = 'pnpm start'
runImage = 'node:18-slim'

[healthcheck]
cmd = 'curl -f http://localhost:3000/health || exit 1'
interval = '30s'
timeout = '10s'
retries = 3

[deploy]
startCommand = 'pnpm start'
restartPolicy = 'always'
healthcheckTimeout = 10
healthcheckInterval = 30

[variables]
NODE_ENV = 'production'
PORT = '3000'